### ISSUE TITLE
Localization of exception messages

### ISSUE THREAD

**Issue by quincycs** [bitstadium/HockeySDK-Windows#108]
Is it possible for exception messages to always be logged in english?

Seems like the same exception is being put into different groupings because of simply the language difference.

**Comment by izikl** [comment]
@quincycs is this something you are experiencing after upgrading to 4.1.6?
I wonder if it is related to [this commit](https://github.com/bitstadium/HockeySDK-Windows/commit/0e915f47b315628b7aeef3faabea1d75ca41dec5#diff-65f8452cb8fe70273bc9ed1125f659cbR151).

**Comment by quincycs** [comment]
@izikl It is an issue with every version of HA.  More like it seems like an issue with .net in general.

**Comment by schuettecarsten** [comment]
I doubt that this is possible because the exception was already created with a message string outside of HockeyApp.

**Comment by quincycs** [comment]
Welll maybe HA (since acquired by MSFT) can get the.net team to add a new parameter to toggle this functionality

**Comment by elamalani** [comment]
@quincycs This doesn't look like an HockeySDK issue and can't be fixed by our team. I'm closing this issue for now but thanks for your input.
