### ISSUE TITLE
Crash details show offset as decimal value, shouldn't it be hex?

### ISSUE THREAD

**Issue by schuettecarsten** [bitstadium/HockeySDK-Windows#113]
Crash details show information like this:

```
Thread 2 Crashed:
0   Test.Uap10                        0x00007ff99ef17c18 0x00007ff99dd40000 + 18709528
```

The last number, 18709528, is decimal. I think it should be hex to make it more readable.

**Comment by elamalani** [comment]
@schuettecarsten Thanks for sharing your feedback but this issue has nothing to do with the HockeySDK. Unfortunately, we don't have any plans to change this in HockeyApp. I'll close the ticket for now but please feel free to open another ticket if you have more questions. Thanks!
