### ISSUE TITLE
An app might hang due to FlushManager.Flush()

### ISSUE THREAD

**Issue by hizzz** [bitstadium/HockeySDK-Windows#116]
[I have seen twice an application with hovering UI](https://drive.google.com/open?id=0By3MVvpUQlWkVTRhWjdIeDBveDQ)

Looks like the following code is dangerous due to deadlock:
`this.storage.EnqueueAsync(transmission).ConfigureAwait(false).GetAwaiter().GetResult();`

**Comment by MatkovIvan** [comment]
Hi @hizzz,

Thanks for getting in touch and sorry for long delay.
Unfortunately, I couldn't reproduce this issue locally and information from your screenshot isn't enough to discover the problem. But I can to say that it happens on processing unhandled exception (writing data to disk) from your application.
Could you please clarify next things:
- On what platform do you have this problem? (probably UWP, but I want to be sure)
- What kind of original exception caused this issue? Where does it happen (in some system/UI event or something else)?
- Also very useful would be information where execution is freezing in a worker thread.

Best,
Ivan
