### ISSUE TITLE
Feature Suggestion: Cmdline tool to get symbolic stack trace

### ISSUE THREAD

**Issue by quincycs** [bitstadium/HockeySDK-Windows#117]
Hey all,

I'm interested in helping build a cmdline tool, looking for feedback, and whether others would be interested as well.

Inputs
1. Non-symbolic stack trace (lots of base address)
2. Symbols 

Output
1. Symbolic stack trace.

**Implementation Option 1.**
1. Create new version inside HA interface.
2. Upload symbols to HA interface. (Not sure all formats supported here.  Is there a way of uploading symbols without dev center involved?)
3. Use HA public API for 'post custom crash' https://support.hockeyapp.net/kb/api/api-crashes
4. Hopefully step3 provides a crash log id.  Then use HA public API for searching or fetching for the specific uploaded crash
5. Verify downloaded crash is symbolicated.

========
Motivation

If you have analytics / metrics / exceptions going into a different system, its easier to get the symbolicated stack trace thru a cmd line tool instead of send duplicate data to one system and additionally to HA.

**Comment by elamalani** [comment]
@quincycs Thanks for using HockeyApp and suggesting this feature. We have decided to not prioritize this to be supported in HockeyApp. So I'll close this issue for now. But feel free to reach out to us if you have any questions. Thanks!
