### ISSUE TITLE
Detect new version of package

### ISSUE THREAD

**Issue by bezysoftware** [bitstadium/HockeySDK-Windows#118]
Does the SDK allow detecting new version of alpha package & updating automatically? Or at least manually by redirecting to the download page?

**Comment by TroubleMakerBen** [comment]
Hey @bezysoftware,

sorry for the long wait. Yes, it does. Please [check out our knowledgebase](https://support.hockeyapp.net/kb/client-integration-windows-and-windows-phone/hockeyapp-for-applications-on-windows#beta-distribution).

Best,
Benjamin

**Comment by bezysoftware** [comment]
That's available only for windows phone. Who develops for wp these days? Why is it not available for uwp?
