### ISSUE TITLE
Crashes after resuming from suspension

### ISSUE THREAD

**Issue by ArefGihuni** [bitstadium/HockeySDK-Windows#120]
to reproduce it:
On ARM, open the app, luck the screen. after a few minutes unlock it. The app is gone! 
(Can't reproduce it using Visual Studio lifecycle events)

this is the error:

> 
> The underlying compression routine could not be loaded correctly.
> ...
> Unable to load DLL 'clrcompression.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)

I've upgraded to 'Microsoft.NETCore.UniversalWindowsPlatform' 5.3.3

Min version Windows 10 Build 10240

**Comment by MatkovIvan** [comment]
Hi @ArefGihuni 

Thanks for getting in touch!
I already answered you [here](https://github.com/bitstadium/HockeySDK-Windows/pull/112).
> It can be related to nuget package `Microsoft.EntityFrameworkCore.Sqlite`
Also, it seems to be related only to `EntityFrameworkCore.Sqlite` version 1.1.* , version 1.0.* doesn't have such issue. See info [here](https://github.com/dotnet/corefx/issues/13914#issuecomment-279588468).


Let us know if you are still facing this problem.

Best,
Ivan

**Comment by TroubleMakerBen** [comment]
Hi @ArefGihuni,
we haven't heard from you in a while so I'm closing this issue. If this still happens, please reopen the issue and provide us with some more context.

Best,
Benjamin
