### ISSUE TITLE
Question: Can HockeySDK and IoT

### ISSUE THREAD

**Issue by mjmeans** [bitstadium/HockeySDK-Windows#125]
Will HockeySDK work with Windows IoT apps?

**Comment by edoust** [comment]
Yes that is possible, use the UWP SDK

**Comment by mjmeans** [comment]
I've used the UWP SDK. Added to app.cs the HockeyClient.Current.Configure call like in the sample, using the app's id. Added several TrackEvent calls. Created a package. Uploaded to hockyapp site from within VS 2017. Downloaded the package form hockey app. Added the package to the Windows IoT Core flash image (flash.ffu). FLash the SD card and booted the device. My app boots.

So now I'm checking updating. I made a small change and uploaded a new version to hockeyapp site from within VS. Then I restarted by Windows 10 IoT device running the app and it doesn't update or notify me of an available update.

**Comment by edoust** [comment]
> So now I'm checking updating. I made a small change and uploaded a new version to hockeyapp site from within VS. Then I restarted by Windows 10 IoT device running the app and it doesn't update or notify me of an available update.

AFAIK that is the expected behavior. HockeyApp is not meant to be an alternative to the Windows Store deployment, it only provides the possibility to sideload (beta) app packages.

Why can't you use the Windows Store for deployment? Then you could programatically trigger the update, [see here](https://docs.microsoft.com/en-us/windows/uwp/packaging/self-install-package-updates)

**Comment by mjmeans** [comment]
Windows Phone apps will auto-update using HockerApp. So Windows IoT devices should also. They are very similar platforms with respect to being locked down and using ARM processors. So the expectation is that HockeyApp will be used for all development purposes (including updating the app during development and testing).

I will not distributing a commercial product. This is for a beta test only. My customer needs to do certification and QC testing before they decide to buy the product design I come up with. I need to get crash reporting and usage data during this testing for my own QC. These purposes are not appropriate for Windows Store distribution (which is why HockeyApp exists in the first place). So I don't want Windows Store (because it's not appropriate and costs money), and I don't want Azure IoT Hub (because it's inappropriate for beta use and costs even more money after the first 30 days).

**Comment by TroubleMakerBen** [comment]
Hey @mjmeans,

thx for explaining your motivation and needs.
Unfortunately, we don't support auto-update specifically for IoT devices.
We're currently hard at work on [AppCenter](https://www.hockeyapp.net/appcenter/about/) so it's not very likely that HockeyApp will get the required functionality.

Best,
Benjamin

**Comment by mjmeans** [comment]
Will AppCenter support auto-update for Windows IoT devices?

**Comment by TroubleMakerBen** [comment]
Hey,
it's currently not possible to do side-loading on Windows IoT devices so App Center has the same limitation that HockeyApp has at the moment.

Best,
Benjamin
