### ISSUE TITLE
HockeyApp and Windows 10 IoT

### ISSUE THREAD

**Issue by mjmeans** [bitstadium/HockeySDK-Windows#127]
So, I'm developing a UWP app on Windows 10 IoT using HockeyApp to tack exceptions. HockeyApp is not able to automatically deploy updates to Windows 10 IoT.

I was told that I should use Windows Store to manage app updates. So I did that. There were two issues. 1. In order to use Windows Store I had to buy a company account instead of a personal account so that I could sign up for the OEM Preinstallation program so that I could download the Windows Store signed appx package. 2. Windows Store requires the app to be compiled as Release instead of Debug, thus eliminating most of the trace symbols.

So now I have the preinstallation appx packages signed by Windows Store that I can use to create preinstallation device images (flash.ffu) which is used to create the initial Windows 10 IoT disk image with the device already installed.

However, now I'm getting crashes and crash traces and the resulting crash App Traces lack almost all symbols. Windows Store allows the downloading the symbol file for crash analysis, but I don't see a way to upload the symbol file to the HockeyApp site so that the App Traces make sense.

So HockeyApp fails to be of much use for UWP apps for Windows 10 IoT Core that are managed by Windows Store.

Is there a solution for this?

**Comment by TroubleMakerBen** [comment]
Hey @mjmeans,

thx for getting in touch.

Please checkout [our knowledgebase article](https://support.hockeyapp.net/kb/client-integration-windows-and-windows-phone/how-to-upload-symbols-for-uwp-application). You can upload the symbol file to HockeyApp and get symbolicated stacktraces.

Best,
Benjamin

**Comment by TroubleMakerBen** [comment]
I'm closing this issue as I haven't heard from you in about a month. Please get in touch if there's anything we can do to help you.

Best,
Benjamin
