### ISSUE TITLE
Wpf Application Update MSI.Error - using HockeyClient.Current.CheckForUpdatesAsync

### ISSUE THREAD

**Issue by delvier** [bitstadium/HockeySDK-Windows#137]
I have problem using CheckForUpdatesAsync.

After msi package gets downloaded ans installer is launch, I get the following error:

![image](https://user-images.githubusercontent.com/1397476/36589748-b4fa8dca-188c-11e8-8a58-9398048cd101.png)

Logs of msi installer shows the following:
```
=== Verbose logging started: 2/23/2018  7:21:23  Build type: SHIP UNICODE 5.00.10011.00  Calling process: C:\Windows\System32\msiexec.exe ===
MSI (c) (40:C8) [07:21:23:897]: Font created.  Charset: Req=0, Ret=0, Font: Req=MS Shell Dlg, Ret=MS Shell Dlg

MSI (c) (40:C8) [07:21:23:897]: Font created.  Charset: Req=0, Ret=0, Font: Req=MS Shell Dlg, Ret=MS Shell Dlg

MSI (c) (40:D8) [07:21:23:906]: Resetting cached policy values
MSI (c) (40:D8) [07:21:23:906]: Machine policy value 'Debug' is 2
MSI (c) (40:D8) [07:21:23:906]: ******* RunEngine:
           ******* Product: C:\Users\pljanot\AppData\Local\Temp\tmp65C9.msi
           ******* Action: 
           ******* CommandLine: **********
MSI (c) (40:D8) [07:21:23:906]: Note: 1: 2203 2: C:\Users\pljanot\AppData\Local\Temp\tmp65C9.msi 3: -2147286960 
MSI (c) (40:D8) [07:21:23:908]: MainEngineThread is returning 1620
=== Verbose logging stopped: 2/23/2018  7:21:23 ===
```

I'm using classic publish option via visual studio when uploading artifacts to Hockey.Server.

Is there anything I'm doing wrong or missing ?

I also described this problem on stack:
[stack thread](https://stackoverflow.com/questions/48934884/wpf-application-update-threw-hockey-sdk)

**Comment by MatkovIvan** [comment]
Hi @delvier,

Thanks for getting in touch!
Could you please check if you able to install this MSI package without HockeyApp distribution? It looks like the package is damaged and that issue isn't related to HockeyApp SDK.
Let us know if it's installing OK locally, but not after distribution with HockeyApp.

Best,
Ivan

**Comment by delvier** [comment]
I see your point. 

MSI package downloaded via update mechanics (file under %temp% dir), it's somehow damaged (cannot be installed)

I'm using visual studio menu to distribute my application to Hockey Server. (HockeyApp->DistributeApp)
I thought that's enough to perform successful update via HockeySdk, probably I miss something.

**Comment by naimo84** [comment]
Hey guys,

I'm having exactly the same problem. My Wix MSI setup file is installaing probably, if I install it manually. If I distribute it via HockeyApp, it fails.

Like @delvier said, "MSI package downloaded via update mechanics (file under %temp% dir), it's somehow damaged (cannot be installed)"

I also have tried to distribute the Release Folder --> same problem.

Is it just a Error 40 and I have to RTFM? ;)

**Comment by TroubleMakerBen** [comment]
Hi @naimo84,

can you compare the two binaries (the one you can successfully install locally and the one from hockeyapp) and see if they are identical?
This doesn't seem to me like it's an SDK issue but I'm not sure.

**Comment by nabeelio** [comment]
I'm running into this issue... not sure what to do. Visual Studio is just uploading the contents of my build folder... I'm not generating an MSI (Project -> HockeyApp -> Distribute, same as @delvier). So I think that's happening on the server side? I can open the MSI that gets downloaded to the temp directory in 7-zip and the files are in there. I'm trying to find some details/docs on how the MSI is generated, etc.

The executables in my build directory and the one downloaded appear to be identical.

**Comment by thyeggman** [comment]
@nabeelio Can you run the executable that is created in your build directory?  How about the one that is downloaded?  If you could give a more detailed set of repro steps that would be super helpful too.  If the MSI fails and produces as log like delvier's, please provide that as well.
