### ISSUE TITLE
UWP "Telemetry item length must not exceed 65536"

### ISSUE THREAD

**Issue by biz0n** [bitstadium/HockeySDK-Windows#138]
When I send crash with some description, sometimes I received this error from hockeyapp server
`{"itemsReceived":1,"itemsAccepted":0,"errors":[{"index":0,"statusCode":400,"message":"Telemetry item length must not exceed 65536"}]}`
And this crash didn't appear in dashboard. It's impossible to know how many information I can write to description and I can't fix description after failed sent.
Crashes with description from xamarin android sends normally

**Comment by TroubleMakerBen** [comment]
Hi @biz0n,

I'm a little confused. Are you trying to send a crash or handled exception via our `trackEvent`-API? 
You also mention Xamarin Android. Are you building a Xamarin app (our xamarin SDK does not support UWP) or a UWP app?

That said, the length of the description field is the 65536 characters, are you asking to increase this limit?

Best,
Benjamin

**Comment by biz0n** [comment]
@TroubleMakerBen 
There are two applications: UWP and Android. I try to send log with crash
Code from UWP app
```
HockeyClient.Current.SetExceptionDescriptionLoader(ex => GetApplicationLog());
```
Code from Android app:
```
CrashManager.Register(context, applicationId, new MyCrashManagerListener());
...
class MyCrashManagerListener : CrashManagerListener
{
    public override string Description => GetApplicationLog();
}
```
Log size ~50000 symbols
On Android I have no problem with log, but on UWP I received error message about telemetry item length.

> That said, the length of the description field is the 65536 characters, are you asking to increase this limit?

Yes, could You increase this limit?

Thank You!

**Comment by TroubleMakerBen** [comment]
@biz0n 
now I understand what you are doing. I think the reason is that your description on Windows might be just way longer than the one on Android.

As we are moving to [App Center](https://appcenter.ms), we won't increase the size limit of the description field. I was asking because I wasn't sure what you were asking for.

Best,
Benjamin

**Comment by biz0n** [comment]
@TroubleMakerBen 
We limit description size on UWP and Android
It will be great if server ignore long description and save crash without it. Now we loose important information about crashes.

**Comment by TroubleMakerBen** [comment]
Hi @biz0n,
I understand what you are saying but we are not going the behavior for HockeyApp for the reasons that I explained above.
As a workaroud you need to limit the size of the description field.

Thx for understanding and for using HockApp!
Benjamin
