### ISSUE TITLE
Windows 10 Universal Windows Platform (UWP) - Feedback

### ISSUE THREAD

**Issue by mieliespoor** [bitstadium/HockeySDK-Windows#147]
At present the UWP SDK does not allow us to use the Feedback option as is the case with other platforms. What are the plans of including this, or what other options are available?

I am reading this, and it seems that this is the recommended path suggested by Microsoft. https://docs.microsoft.com/en-us/windows/uwp/monetize/launch-feedback-hub-from-your-app

Any opinions?

**Comment by elamalani** [comment]
@mieliespoor Thanks for using HockeyApp. Our team is working on [App Center](http://appcenter.ms) which is the next generation of HockeyApp. We don't plan to work on supporting Feedback service in HockeyApp UWP SDK.

Please let us know if you have any questions.

**Comment by mieliespoor** [comment]
Great thanks. I somehow missed the announcement on AppCenter. I will be investing more in that going forward.
