### ISSUE TITLE
sendAutomatically instead of sendWithoutAsking

### ISSUE THREAD

**Issue by ranjan-2209** [bitstadium/HockeySDK-Windows#150]
In https://github.com/bitstadium/HockeySDK-Windows, there is `sendWithoutAsking`, we should be using `sendAutomatically` instead of `sendWithoutAsking`.

**Comment by ElektrojungeAtWork** [comment]
Hey @ranjan-ranjan,

I am not sure I understand what you are asking or reporting here. Are you proposing a rename of the `sendWithoutAsking` API to `sendAutomatically`?

Best,
Benjamin

**Comment by ranjan-2209** [comment]
`await HockeyClient.Current.SendCrashesAsync(/* sendWithoutAsking: true */);`
  should be 

`await HockeyClient.Current.SendCrashesAsync(/* sendAutomatically: true */);`

**Comment by guperrot** [comment]
We fixed the readme, thanks for the feedback.
