### ISSUE TITLE
Exception when checking for updates

### ISSUE THREAD

**Issue by endikamontejo** [bitstadium/HockeySDK-Windows#24]
Good afternoon.

I am running an WPF app in Windows 7 64 bits with Visual Studio  2013, using HockeySDKCore 2.2.2 and HockeySDKWPF 2.2.2. Following this link http://support.hockeyapp.net/kb/client-integration-android-other-platforms/hockeyapp-for-windows-wpf-apps, I am trying to send crashes asynchronously and checking for updates.

The part of sending crashes asynchoronously is working fine but I am getting an Exception on the code related to check for updates. When I arrived to the code I get a NullReferenceException.
But even more, when I have a version to update I get the previous exception plus a RunTimeBinderException, where I am told that the HockeyApp.ResourceWrapper doesn't contain a definition for UpdateHeader.

Any tip of what can I be doing wrong?

Thank you

![exceptiononstartupjpg](https://cloud.githubusercontent.com/assets/5689593/5662387/b87034b0-9738-11e4-9f69-4a0a6eae71d8.JPG)
![hockeyappcrashwhenneedtoupdate](https://cloud.githubusercontent.com/assets/5689593/5662386/b86c3518-9738-11e4-9a8d-144da25c3ee2.JPG)

**Comment by andreasmo** [comment]
Your looking at first chance exceptions (for an explanation see http://blogs.msdn.com/b/davidklinems/archive/2005/07/12/438061.aspx). These are handled in our code and do not mean anything is wrong. To disable breaking on this exceptions you can change the settings under Debug > Exceptions in Visual Studio.
