### ISSUE TITLE
Issue with signing package

### ISSUE THREAD

**Issue by endikamontejo** [bitstadium/HockeySDK-Windows#26]
Hi!
As I need to sign my assembly and none of HockeyApp (HockeySDK.WPF.2.2.2) and HockeyAppPCL (HockeySDK.Core.2.2.2) have a strong name I need to add them a strong name.

For this, I sign your packages with the package StrongNaming https://www.nuget.org/packages/Nivot.StrongNaming/.

The problem after signing with StrongNaming is that I have realised that HockeyApp packages stop working. They throw an exception (which doesn't crash the app) and do nothing.

Can you give me any tip of how can I sign these packages?

**Comment by ashtom** [comment]
We believe that the only solution is to compile our WPF and Core libraries from source and adjust the references between them to work with StrongNaming.

**Comment by endikamontejo** [comment]
Yep, think so. Thanks ;)
