### ISSUE TITLE
Send feedback with attachment and empty subject line gives wrong error message

### ISSUE THREAD

**Issue by sdouglas-macadamian** [bitstadium/HockeySDK-Windows#31]
If you try to send feedback from a Windows 8.1 device without a message, but with an attached file the following error is shown:

```
Could not send Feedback. Are you sure you're connected to the internet?
```

If you try to send without a message _and_ without an attached file, a different (and presumably correct) error is shown:

```
Please enter a message or add an image as an attachment.
```

**Comment by elamalani** [comment]
@LaviniaC Sorry for the super late follow-up on this issue. Are you still running into this error? I'll close it for now but please feel free to reopen if you have any questions. Thanks!
