### ISSUE TITLE
AsyncLock and HttpClient

### ISSUE THREAD

**Issue by mrsmitty** [bitstadium/HockeySDK-Windows#38]
In HockeySDK_Portable45 HockeyApp.Extensions.AsyncLock the following
`return wait.IsCompleted ?
                        m_releaser :
                        wait.ContinueWith((_, state) => (IDisposable)state,
                            m_releaser.Result, CancellationToken.None,
            TaskContinuationOptions.ExecuteSynchronously, TaskScheduler.Default);`

The option `TaskContinuationOptions.ExecuteSynchronously` can cause deadlocks with HttpClient. This should only be used with short running operations. See:
https://msdn.microsoft.com/en-us/library/system.threading.tasks.taskcontinuationoptions(v=vs.110).aspx

**Comment by mihailsm** [comment]
@mrsmitty do you have a unit test repro that cause the deadlock?
