### ISSUE TITLE
Update Manager shutdownAction not called before Install

### ISSUE THREAD

**Issue by LaviniaC** [bitstadium/HockeySDK-Windows#39]
I see it is set but it's never used. 
UpdateWindow calls Install which will terminate the process.

**Comment by mihailsm** [comment]
Lavinia, could you please provide a test project which reproes the issue and describe the repro steps?

**Comment by LaviniaC** [comment]
Repro project: [HockeyAppTest.zip](https://github.com/bitstadium/HockeySDK-Windows/files/190885/HockeyAppTest.zip)
Repro steps:
1. Run the app
2. Click install on the update window

Expected result: after the download of the installer is completed, before starting the .msi, the shutdownAction code should be executed => message should be logged before the app is closed.

Current result: the app is closed without calling the shutdownAction method

**Comment by mihailsm** [comment]
Thanks, we we will look into it and will get back to you

**Comment by taspeotis** [comment]
https://github.com/bitstadium/HockeySDK-Windows/blob/7bd7d8a3c2f9095506c6bd7f832fd755cbd48741/HockeySDK_WPF/UpdateManager.cs#L27

`_shutdownActions` is assigned but never called. HockeyApp just unceremoniously calls `Environment.Exit(0)`.

https://github.com/bitstadium/HockeySDK-Windows/blob/7bd7d8a3c2f9095506c6bd7f832fd755cbd48741/HockeySDK_WPF/IAppVersionExtensions.cs#L81

Infuriatingly, `shutdownActions` is mandatory.

```
if (autoShowUi)
{
  if (shutdownActions == null)
    throw new ArgumentException("You have to provide a shutdownRequest-Action if using autoUi == true!");
}
```

I think it should be optional, and if not specified HockeyApp would do something to the effect of:

```
var currentApplication = Application.Current;

if (currentApplication == null)
  Environment.Exit(0); // No return.

currentApplication.Shutdown();
```

**Comment by elamalani** [comment]
@LaviniaC Sorry for the super late follow up on this issue. Are you still running into this error? I'll close it for now but please feel free to reopen if you have any questions. Thanks!
