### ISSUE TITLE
Description for Exceptions logged via HockeyApp.HandleException is empty

### ISSUE THREAD

**Issue by wldevries** [bitstadium/HockeySDK-Windows#41]
Some Exceptions are not handled on the Dispatcher or on the AppDomain and need to be registered manually. In that case however the description is a single '-' in the overview which is not very helpful.

![image](https://cloud.githubusercontent.com/assets/1745610/14428710/85f0daae-fffa-11e5-80a0-96f2c8c6e2bf.png)

**Comment by frogger3d** [comment]
Also not only this happens, but all Exceptions logged this way are bunched into the same crash group.

**Comment by frogger3d** [comment]
Okay I tried the HockeyClient.DescriptionLoader, but it seems to be something different. It should provide the description that the user types.

**Comment by mihailsm** [comment]
[HockeyClient.SetExceptionDescriptionLoader](http://support.hockeyapp.net/kb/client-integration-windows-and-windows-phone/hockeyapp-for-windows-wpf-apps#advanced-options) API is controlling the log tab content, it is not affecting the crash description. @wldevries, could you please clarify what app type are you using (WPF, UWP, WinRT, etc) and provide a code sample that reproes this issue so that we can work on it on our side?

**Comment by wldevries** [comment]
I'm using the WPF app type. The following is in my App.Startup event handler:

            //configure HockeySDK client
            HockeyClient.Current.Configure("{app id}")
                .RegisterCustomDispatcherUnhandledExceptionLogic(ex => this.Shutdown(-1))
                .RegisterCustomUnhandledExceptionLogic(ex => this.Shutdown(-1));

            // These handlers will also log first chance exceptions such as the cannot connect to BtsServer
            //.RegisterCustomUnobserveredTaskExceptionLogic(ex => HandleUnObservedTaskException(ex))
            //.RegisterDefaultUnobservedTaskExceptionHandler();

            (HockeyClient.Current as HockeyClient).SetContactInfo(Environment.MachineName, null);

            //send stored crashlogs to HockeyApp server
            await HockeyClient.Current.SendCrashesAsync();

And the following is how I log an `Exception`. Note that this is not how we use it in our application, but it has the same effect. The description of the Crash will be a single '-'.

        private void Crash(object sender, RoutedEventArgs e)
        {
            try
            {
                throw new InvalidOperationException("Something bad happened here");
            }
            catch (Exception ex)
            {
                (HockeyClient.Current as HockeyClient)?.HandleException(ex);
                Environment.Exit(-1);
            }
        }

The reason we do this is because the Prism library swallows any Exceptions that occur in `DelegateCommand` and the navigation system. Because the Exceptions are handled by Prism they are not picked up by `AppDomain.CurrentDomain.UnhandledException` nor by `Dispatcher.UnhandledException`.

**Comment by mihailsm** [comment]
Thanks, @wldevries. Acknowledge the issue, we will be working on fixing it.

**Comment by anlinde** [comment]
Please note that reporting non fatal reports like unhandled exceptions is currently not officially supported but we are working on it. One limitation you should be aware of, is the API rate limit of 60 requests per minute. So sending a lot of non fatal errors could cause not getting the fatal errors in time. The SDKs will try to resend pending data later if the server rejected it.

**Comment by wldevries** [comment]
Actually to us these errors are fatal, we even fatally fail manually on navigation errors in Prism.
