### ISSUE TITLE
Include computer name in crash reports

### ISSUE THREAD

**Issue by wldevries** [bitstadium/HockeySDK-Windows#42]
This would really help for wide deployments of WPF applications.

**Comment by anlinde** [comment]
Hi, this would be a privacy issue. So it is unlikely that we'd add that on our end.

**Comment by frogger3d** [comment]
Were we to ignore these privacy issues should we use the HockeyClient.Device for it?

**Comment by anlinde** [comment]
I am not sure what you are referring to, could you please add a link?

**Comment by frogger3d** [comment]
https://github.com/bitstadium/HockeySDK-Windows/blob/develop/HockeySDK_Portable/HockeyClient.cs#L227

It seems that the Devices property is a bit wonky, it probably is only used for mobile apps. When you open the Devices tab on the website for a WPF app you get a big black block.

![image](https://cloud.githubusercontent.com/assets/1745610/14430047/425162f4-0000-11e6-98aa-628966a3eafd.png)

**Comment by anlinde** [comment]
We'll put it on our backlog. Thanks for the hint.

**Comment by frogger3d** [comment]
Regarding adding custom log data, could you point me in the right direction? Neither the [integration guide](http://support.hockeyapp.net/kb/client-integration-windows-and-windows-phone/hockeyapp-for-windows-wpf-apps) nor the [demo app](https://github.com/bitstadium/HockeySDK-WindowsDemo) indicate how to do it.

The `HockeyClient.HandleException` method does not seem to provide any hooks for adding additional metadata.

**Comment by anlinde** [comment]
@mihailsm could you please help?

**Comment by mihailsm** [comment]
@wldevries, we added a documentation on how to add custom log data, here is the link: [HockeyApp for WPF : Advanced Options ](http://support.hockeyapp.net/kb/client-integration-windows-and-windows-phone/hockeyapp-for-windows-wpf-apps#advanced-options)
