### ISSUE TITLE
Suggestions when developing a new App with HockeySDK

### ISSUE THREAD

**Issue by wldevries** [bitstadium/HockeySDK-Windows#43]
We were originally looking at Application Insight to provide both crash reporting and telemetry analysis for an existing application. All the features are there and we are especially interested in the telemetry. 

Looking at the preseason branch it seems that the entire SDK is going to be a carbon copy of the current Application Insight SDK. Would it be wise to target the Application Insight SDK for now and switch over later this year to HockeyApp after it has been merged with both Application Insight and Xamarin Insight?

Second question, could you provide a tentative timeline for HockeyApp and give an estimation when it will be feature par with Application Insight?

**Comment by anlinde** [comment]
Hello,

we recommend to start with the HockeyApp SDK as the Application Insights Devices experience is deprecated and will be turned off in June. From then on HockeyApp is the only interface to your data. We are working hard in adding features but we can't give definite timelines on when which features will be available.

We already support users, sessions and custom events. We will continue to improve these features over the next weeks and months. There is no tentative timeline publicly available when we add which improvements other than what we post on our Preseason page and blog posts.

Best,
Andreas

**Comment by wldevries** [comment]
In our case we are looking at adding telemetry as soon as possible. Since we are not included in the preseason (and preseason is not available as a WPF package) we are mainly looking at the possibilities in the future. At the moment the preseason branch seems to be almost the same as the Application Insights API except for the namespace. Don't you agree that for now it might be interesting to tentatively integrate the Application Insights SDK for in house evaluation and refactor the namespace and update to a HockeyApp application ID later?

**Comment by anlinde** [comment]
There will be a migration path for Application Insights Users to HockeyApp. For this specific scenario of yours with WPF your idea looks to be the best approach. But just saying, the Application Insights UI will not work for much longer for devices apps.
