### ISSUE TITLE
WinForms - use GetEntryAssembly when retrieving version

### ISSUE THREAD

**Issue by bvanderw** [bitstadium/HockeySDK-Windows#44]
In HockeyPlatformHelperWinForms, the AppVersion property has the following code:

`_appVersion = Assembly.GetExecutingAssembly().GetName().Version.ToString();`

This returns the version of the base HockeyApp assembly. 

GetEntryAssembly will return the version of the application.

**Comment by mihailsm** [comment]
Windows Forms SDK is not yet published and is not supported, you can contribute to it it, we welcome pull requests as always.
