### ISSUE TITLE
TelemetryClient is internal

### ISSUE THREAD

**Issue by zumicts** [bitstadium/HockeySDK-Windows#46]
Limited to only being able to track even data using the simple method inside the `HockeyClient`, which lacks a lot of the parameters available in the `TelemetryClient`.

**Comment by zumicts** [comment]
PR #47 fixes this by adjusting the method's signature.

**Comment by mihailsm** [comment]
Currently TelemetryClient is merged into HockeyClient and exposes all of its methods, take a look on our doc at https://support.hockeyapp.net/kb/client-integration-windows-and-windows-phone/how-to-integrate-hockeyapp-with-application-insights
