### ISSUE TITLE
Support for logging events with custom parameters in UWP apps

### ISSUE THREAD

**Issue by martinsuchan** [bitstadium/HockeySDK-Windows#48]
Right now ("HockeySDK.UWP": "4.1.0-build65440") it's only possible to log events in UWP apps like this:
`HockeyClient.Current.TrackEvent("folderSelected");`

There is no option to log events custom parameters like:
```
{
"event":"folderSelected",
"params":{"name":"inbox"}
}
```

**Comment by mihailsm** [comment]
This is done now as a part of integration with Application Insights, described in details at 
https://support.hockeyapp.net/kb/client-integration-windows-and-windows-phone/how-to-integrate-hockeyapp-with-application-insights#track-event
