### ISSUE TITLE
Dispose MD5CryptoServiceProvider

### ISSUE THREAD

**Issue by galich** [bitstadium/HockeySDK-Windows#49]
From https://github.com/bitstadium/HockeySDK-Windows/blob/master/Src/Kit.WPF/HockeyClientWPFExtensions.cs#L260

```MD5 md5 = new MD5CryptoServiceProvider();```

MD5CryptoServiceProvider is IDisposable, but Dispose is never called.

**Comment by martinsuchan** [comment]
The instance of MD5CryptoServiceProvider should be either disposed after use or only one instance should be kept over the app lifetime.

**Comment by galich** [comment]
Related to issue #59 

Perhaps MD5 from CNG is better than MD5 from CSP.
