### ISSUE TITLE
Vague documentation for WP/WinRT/UWP apps

### ISSUE THREAD

**Issue by martinsuchan** [bitstadium/HockeySDK-Windows#50]
Some notes to the SDK documentation:
- there is no mention how to initialize **Windows Phone 8.1 WinRT (wpa81)** apps in the guide even though HockeySDK.WINRT SDK supports them as well.
- it's not clear if this line should placed in the App constructor on the first line, or after InitializeComponent() or it does not matter:
  **HockeyClient.Current.Configure(“Your_App_ID”);**
- there is no **SendCrashesAsync** method in the HockeyClient SDK for WINRT and UWP (4.1.1-build10067). The guide suggest I need to use this call in WINRT apps.
- there is no event **Application.Launching** in WINRT or UWP apps where I should place the call mentioned above.

**Comment by martinsuchan** [comment]
Probably related issue - the guide on **rink.hockeyapp.net** how to integrate UWP SDK is completely empty:

![capture](https://cloud.githubusercontent.com/assets/3041397/16176812/b2436af4-3619-11e6-8260-04ad22baa272.PNG)

**Comment by mihailsm** [comment]
Hi Martin, we improved our documentation at https://support.hockeyapp.net/kb/99498/edit
