### ISSUE TITLE
HockeyClient.Current.Configure could not be found

### ISSUE THREAD

**Issue by dajbych** [bitstadium/HockeySDK-Windows#52]
I cannot execute
`Microsoft.HockeyApp.HockeyClient.Current.Configure("abcdef");`
because `HockeyClient.Client` returns `IHockeyClient` which does not contain definition of the `Configure` method.

This issue is new to HockeySDK for UWP 4.1.1.

**Comment by mihailsm** [comment]
Take a look on our demo project, it is done there at 
https://github.com/bitstadium/HockeySDK-WindowsDemo/blob/master/UWP/HockeyAppDemoUwp/cs/App.xaml.cs#L34

**Comment by boarder2** [comment]
Hopefully @dajbych found the answer, since it's not particularly clear from @mihailsm response.  For anyone else looking back at this:

You need to add `using Microsoft.HockeyApp;` instead of using the fully qualified path since `.Configure` is now an extension method.
