### ISSUE TITLE
Apps with HockeySDK WP 4.1.1 fails Store certification - CrossGen failed

### ISSUE THREAD

**Issue by martinsuchan** [bitstadium/HockeySDK-Windows#53]
I've added **[HockeySDK WP 4.1.1](https://www.nuget.org/packages/HockeySDK.WP/)** NuGet to my Windows Phone 8.1 Silverlight app and since then I'm unable to submit it to Windows Store. The submission process fails with **[error code(s) 2001](https://msdn.microsoft.com/windows/uwp/publish/resolve-submission-errors?f=255&MSPPError=-2147217396)**.  

After chatting with Microsoft Support we've found out that there is indeed bug in the latest HockeySDK NuGet package - the "compilation in the cloud" fails with:  

> CrossGen failed
> Error processing assembly D:\\data\\PkgProc\\fBVQQ2ARnEa4yjqaJeiH8A\\Extracted\\Microsoft.HockeyAppKit.dll
> Raw error code: 2148733978

This happens on VS2015 Update 3, UWP Tools 1.4.0 and NuGet 3.5.0.1484

**Comment by mihailsm** [comment]
Hi Martin,
it is hard to get from the description what was the error during processing the Microsoft.HockeyAppKit.dll assembly, but it could be the case that this assembly was delayed signed and not strongly named in 4.1.1. We fixed this issue in 4.1.2: https://www.nuget.org/packages/HockeySDK.WP/4.1.2.

Could you please try it and let us know whether it works for you?

**Comment by martinsuchan** [comment]
Hi, there were no problems with app certification with the version 4.1.2, thanks for the update.
