### ISSUE TITLE
Extend API to allow customizations of the send crash dialog

### ISSUE THREAD

**Issue by NachbarsLumpi** [bitstadium/HockeySDK-Windows#56]
Currently SendCrashesAsync() does show a MessageBox, but there is currently no way to customize the dialog of that decision. It would be nice if HockeySDK would invoke a handler which then can display a more fancy dialog window and just return the user decision to send crash reports back to the HockeySDK.

**Comment by elamalani** [comment]
@NachbarsLumpi It sounds like a nice feature to have in our SDK. Unfortunately, we are not adding any customization features in our SDK. If you decide to fork and implement it on your own, consider making it public as it might be useful for the community.

**Comment by NachbarsLumpi** [comment]
This is bad news to hear and certainly has an impact on our evaluation.
