### ISSUE TITLE
AggregateException from TaskScheduler.UnobservedTaskException

### ISSUE THREAD

**Issue by quincycs** [bitstadium/HockeySDK-Windows#61]
![image](https://cloud.githubusercontent.com/assets/2924643/17562742/c5057492-5ef1-11e6-9de8-bf2be3aa2fcb.png)

This isn't helpful info, can we improve it ?  Its got no stacktrace, it doesn't say what exceptions are in the agg exception.  Let's serialize AggregateException better.  App insights has classes that serialized this exception better, it would get out inner exceptions etc.

Also are we sure that unobservedtaskexceptions even crash the app?  I thought they were just exceptions that are handled and wouldn't cause a crash.

Context here is UWP

**Comment by quincycs** [comment]
https://support.hockeyapp.net/kb/client-integration-windows-and-windows-phone/crash-reporting-for-uwp
> Please note that the stacktrace of UnobservedTaskException could be empty as a result of the handler not passing in the exception.

^i just saw this note.  In my case this is wrong, it passes the exception in - its an AggregateException?

**Comment by quincycs** [comment]
https://msdn.microsoft.com/en-us/library/jj160346

seems default is not to crash

**Comment by FatJohn** [comment]
We have the same issue. 
We capture a lot of Task_Unhandled Exception which is come from AggregateException. It's much better to show more info about InnerException
@quincycs we have add some workaround like code below.
`HockeyClient.Current.Configure("youCode Here", new TelemetryConfiguration()
{
	EnableDiagnostics = true,
}).SetExceptionDescriptionLoader(ex =>
{
	if (ex == null)
	{
		return "Exception is null";
	}

	string result = string.Empty;

	if (ex is AggregateException)
	{
		var innerException = ex.InnerException;
		if (innerException == null)
		{
			innerException = ex;
		}

		result = $"InnerException HResult:{innerException.HResult}\r\nName:{innerException}\r\nMessage:{innerException.Message}\r\n{innerException.StackTrace}";
	}
	else
	{
		result = $"Exception HResult:{ex.HResult}\r\nName:{ex}\r\nMessage:{ex.Message}\r\n{ex.StackTrace}";
	}

	return result;
});`
So you can see things in "Description" under crash log

**Comment by quincycs** [comment]
@fatjohn yeah I have a similar "workaround" but I wouldn't say it's a workaround.  It's not a great solution because we can't get symbolized stacktrace this way.   We can just see baseaddress stuff

**Comment by akrantz** [comment]
I also see multiple different crashes grouped under TaskExceptionHolder_UnhandledException. These need to be grouped based on the inner exception info.

**Comment by quincycs** [comment]
I see this fixed!  yay
