### ISSUE TITLE
WinForms platform doesn't work

### ISSUE THREAD

**Issue by Kostusev** [bitstadium/HockeySDK-Windows#64]
WinForms platform doesn't contain `IPlatformService` implementation.
And call `ServiceLocator.GetService<Services.IPlatformService>()` in method `SdkVersionPropertyContextInitializer.GetAssemblyVersion()` throw an exception.

Implementation of `IPlatformService` like for WPF platform is missing.

**Comment by dkackman** [comment]
Hey all,

I've started on filling out the implementation of the WinForms platform. Still a work in progress but crash reporting is working and telemetry is in progress.

Fork is here: https://github.com/dkackman/HockeySDK-Windows/tree/preseason-winforms 

If I can figure out why telemetry events aren't showing up on the dashboard I should have a pull request soon.

Don

**Comment by elamalani** [comment]
@Kostusev Please see the link for WinForms official support.
https://github.com/bitstadium/HockeySDK-windows#winforms-sdk

If you decide to use HockeySDK for WinForms, please look at this pull request #81.
