### ISSUE TITLE
Calling HockeyClient.Current.Configure again should not crash the app

### ISSUE THREAD

**Issue by eshy** [bitstadium/HockeySDK-Windows#69]
I just implemented this SDK for the first time on a WP 8.1 RT app, followed the instructions and placed the Configure call in the OnLaunched method in app.xaml.cs and I got this crash after navigating away and back to the app. 

The exception thrown is from the AppIdentifier setter in [HockeyClient.cs](https://github.com/bitstadium/HockeySDK-Windows/blob/61b30309269d4c67426182de1e1a42cbc71a730c/Src/Kit.Core45/HockeyClient.cs)

An analytics/crash reporting SDK should never throw exceptions, especially when it would be easy enough to ignore and just log a warning or at the very least only throw those exceptions in debug mode.

HockeyApp is not a core functionality of an app, it's a library meant to help the developer. It doesn't help the developer if such a library causes crashes for end users

**Comment by bmourat** [comment]
Hi @eshy 
There is a check now which will not allow performing Configure method more than one time.
