### ISSUE TITLE
Unable to install HockeySDK.WP 4.1.5 into a Windows Phone 8.1 project in a PCL

### ISSUE THREAD

**Issue by geekatwork** [bitstadium/HockeySDK-Windows#73]
When trying to install this I get "Install-Package : Could not install package 'HockeySDK.WP 4.1.5'. You are trying to install this package into a project that targets 'WindowsPhoneApp,Version=v8.1', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.". I know it is something to do with the targets but am unsure on what to edit in the package.

**Comment by elamalani** [comment]
@geekatwork It looks like a very old issue. Is this issue fixed or are you still having issues with the installation? I'll close the issue for now but please feel free to open it again if you'd like any help. Thanks!
