### ISSUE TITLE
UWP (win10) - Conversation about reporting crashes at startup & handled exception tracking

### ISSUE THREAD

**Issue by quincycs** [bitstadium/HockeySDK-Windows#75]
Recently encountered an crash that existed on TH1/TH2 clients.  The first line of OnLaunched() crashed the app due to calling a RS1 API.

The exception was never able to be sent to hockeyapp b/c the app quickly crashed without giving hockeyapp a chance to send it.

**Comment by ashtom** [comment]
This is expected and the same for all platforms. For iOS, we have some special instructions on how to handle those, but it's a complicated process and not widely adopted:
https://support.hockeyapp.net/kb/client-integration-ios-mac-os-x-tvos/how-to-handle-crashes-during-startup-on-ios-and-os-x

**Comment by quincycs** [comment]
why is this expected?  why can't the exception be attempted to be sent at crash time?

**Comment by ashtom** [comment]
After the crash, the app is in an unstable state, so our SDK will not try to spin up new threads to create an HTTPS connection or block the main thread or do other things that might lead to data corruption.

**Comment by quincycs** [comment]
how would sending an exception , lead to data corruption?

**Comment by ashtom** [comment]
Long story is here:
http://landonf.bikemonkey.org/code/objc/Reliable_Crash_Reporting.20110912.html

Same principal applies to all platforms. If you spin up new threads to connect to the internet and wait for their results, other thread continue to run in an unstable state and work on data that is potentially corrupted.

**Comment by quincycs** [comment]
i'm suggesting something like below.  What would lead to data corruption?  Are you saying the crashing thread / application at whole is in an unknown state and its best practice to close it asap b/c its unknown if its doing something destructive?

private async void OnUnhandledException(object sender, UnhandledExceptionEventArgs e)
{
e.Handled = true;
await SendException();

Exit();
}

**Comment by quincycs** [comment]
Is there any suggestions in knowing whether there are groups of users where the application crashes very quickly for them?

**Comment by ashtom** [comment]
Correct, this is what I am saying. Also note that sending the exception might itself fail with an exception, the phone might run out of battery, your car might drive into a tunnel, etc. Y

To work around this, you can modify the SDK or apply a similar pattern as on iOS.

**Comment by quincycs** [comment]
yeah, theres always going to some way its not 100% correct.  But my point is to get better than 0% :).

If you have any suggestions how to do this for win10, would love to hear opinion.  
Really seems like you have to store the exception data somehow at crash time.  True?
Therefore you gotta write code like above OnUnhandledException.

**Comment by ashtom** [comment]
You could check in your OnLaunched() if crashes are stored in the file system and then delay your launch code. You could also do some "trial and error" and only delay the launch code when this happens repeatedly (for example by looking at how many crash logs are stored).

**Comment by quincycs** [comment]
hm, hockeyapp SDK already stores crashes at crash time right?  so i guess it doesn't need to be stored seperately.

so what would it look like after changing hockeyapp SDK?  maybe this?
OnLaunched() 
{
await IHockeyApp.Current.Flush();
}

**Comment by ashtom** [comment]
Sending happens here, but you don't want to `await` every time telemetry items are sent at launch:
https://github.com/bitstadium/HockeySDK-Windows/blob/d0f7b0d3e5c350ddd042d9dea9c87de0444534a0/Src/Kit.Core45/Channels/InMemory/Transmission.cs#L117

The crashes are cached here and then sent through the same channel as other telemetry at the next launch:
https://github.com/bitstadium/HockeySDK-Windows/blob/d0f7b0d3e5c350ddd042d9dea9c87de0444534a0/Src/Kit.UWP/Services/UnhandledExceptionTelemetryModule.cs#L84
You could modify this method to set a flag that the app has crashed and read this at the next launch. You could also set your own unhandled exception handler to do this.

**Comment by quincycs** [comment]
I'll think about it more, but I'm considering two changes to the hockeyapp SDK.

1) expose boolean to know if a stored crash log exists.  might be able to do this without modifying hockeyapp sdk by just doing a check if a file exists in storage.
2) knowing when Flush() is done.

This doesn't seem like this is risky changes to be done to the SDK, b/c users can opt into using this new bool / and making flush return a task makes sense in general.

===
Once those two pieces are complete, then i'll look into when to use them inside app code.

**Comment by ashtom** [comment]
1) Yes

2) The channel is actually a configuration option (see [here](https://github.com/bitstadium/HockeySDK-Windows/blob/d0f7b0d3e5c350ddd042d9dea9c87de0444534a0/Src/Kit.Core45/TelemetryConfigurationFactory.cs#L44)), so you could create a subclass of the existing implementation (or your own implementation with the same interface) and then overwrite Flush to get a callback when it's done.

**Comment by nzthiago** [comment]
@quincycs - do you know if these two improvements are still planned to be done? We have a customer that raised this in October and would like to keep them updated...

**Comment by quincycs** [comment]
@nzthiago I'm not a hockeyapp / MSFT employee.  I reserve the right to change focus. :)  I do think this is a critical issue personally and I do plan on updating this thread when I have implemented something to address the issue.

**Comment by nzthiago** [comment]
@quincycs  👍  no problem, thanks - just checking as it seemed to have momentum back then, no pressure at all

**Comment by quincycs** [comment]
#74 makes this more complex

**Comment by quincycs** [comment]
@nzthiago at least I can attempt to confusingly share what I'm doing for the time being.  (Whiskey should be in hand.)   I currently call  HockeyApp.Current.TrackTrace()  with exception details and session/user info.  Traces are stored in app insights (via the hockeyapp app insights bridge).  But there is downsides to it.

In the App.UnhandledException event , I do e.Handled = true;  then I track trace , flush and wait for a couple seconds with Task.Delay().

Downsides
1. e.Handled = true;  this will stop logging of 'handleable' crashes in the dev center.  Some crashes will still show up in dev center and these are exceptions that you can't handle e.g. OutOfMemory, LayoutCycle.
2. track trace then flush.  This is code that is running while the application is an unknown / unstable state.  If there is any reason/possibility that the code could be running something destructive (e.g. deleting user data) its best to let the app close as fast as possible instead of waiting around for this track trace to complete.  In theory this is what the existing HA SDK functionality is doing at crash time though the difference is they store data to disk then exit - and at next launch then send data over network.  My application there is nothing destructive that could be happening so at crash time i show a dialog saying we will close the application.  User will press 'ok' all the while the track trace code is trying to send the details as fast as possible.  After 5 seconds of the dialog showing but after user pressing ok then I allow the application to close.
3. HA crash info won't send until next launch, and it doesn't actually start initializing until past a second of app life.  With #2 basically forcing my app to live more than 5 seconds the previous crash will be sent to HA during this time.  In theory we could change the HA SDK to send it at crash time instead of next launch - but I figure if the app crashes quickly the user would try to open it again at least once.  If the user does then we'd know about it in HA as well as the traces.

**Comment by elamalani** [comment]
Leaving this issue open for visibility.

**Comment by TroubleMakerBen** [comment]
FYI I just renamed this for people to get a better idea of what's discussed in this issue.
