### ISSUE TITLE
winforms hocket

### ISSUE THREAD

**Issue by rolandh** [bitstadium/HockeySDK-Windows#77]
I see that you have an alpha untested winforms version of hockey, the nuget package however is not published. I have tried adding it as a manual local source but can't figure out how to install it.

Could you publish some instructions on how to import the winforms nuget package manually? I would like to trial and test it for you.

Thanks

**Comment by elamalani** [comment]
@rolandh WinForms SDK is not supported. See here for more information : https://github.com/bitstadium/HockeySDK-windows#winforms-sdk. You can also look at the code in pull request #81. 

You can build and reference the binaries in your project or create a NuGet package, see WPF project as an example.
