### ISSUE TITLE
sending telemetry at high scale

### ISSUE THREAD

**Issue by quincycs** [bitstadium/HockeySDK-Windows#79]
Say I have a very popular UWP application, which could in bursts more than 500 requests per second (which i think is the current limit).  

My scenario is:
Send push notification and when received by all devices (e.g. hundreds of millions lets say) then they all send an event from the background task that is triggered.  NotificationHubs can send something like 2 million push notifications a second.

Does hockeyapp support this scenario?
What should the code look like to support this scenario?  
What happens when requests fail due to too many requests?

**Comment by anlinde** [comment]
The limit of 500 requests per second is per device, not per app on the server (as far as I know). So your scenario should not be a problem.

**Comment by quincycs** [comment]
@anlinde there's got to be a server-side limitation on how many events can be received by server right?  I'm imagining hundreds of million devices all sending an event at the same time.

**Comment by anlinde** [comment]
I don't see a real problem there. But forwarding this to my colleagues.

Just for clarity: the SDKs do not send events instantly, so it will "naturally" be distributed over some time.

**Comment by anlinde** [comment]
So the feedback is the same as mine. The SDK will send it not immediately and if the server rejects it for some reason it will retry later again. You should be covered.

**Comment by quincycs** [comment]
https://social.msdn.microsoft.com/Forums/vstudio/en-US/12e67054-cc4c-48ba-a3a7-54442100e95b/hockeyapp-app-insights-custom-metrics-not-in-sync?forum=ApplicationInsights

Ok. Thx.  I'm coming from a background where I posted the above link a while back ^.  

I think a problematic aspect is the event isn't sent out immediately.  The context is sending the event from a background task.  The user might not have the application even open.

**Comment by anlinde** [comment]
Application Insights is not the backend we are using in HockeyApp for metrics, but the data is forwarded to them too if you have set up a bridging app.

The points I mentioned before still hold true. The SDK should resend if the server rejects the data and sending is done in batches or after 30 seconds after the last send. That should happen no matter wether your app is in the background or not.

**Comment by quincycs** [comment]
Hm interesting.  Yes I have bridged to app insights.  So I assume that hockeyapp does the right thing in terms of sending to app insights in a matter so that events aren't dropped.  Even if events are going into HA at a very high rate per second.  Safe assumption?

Say 1 event is sent from a million devices in a minute.  How long would you say it takes to see all million events be visible in the HA dashboard?   Eg would we have to wait an hour to 12 hours?

**Comment by quincycs** [comment]
I should also ask about when we should expect all 1 million to be inside app insights as well.

**Comment by anlinde** [comment]
Would you mind to contact us via support@hockeyapp.net with these questions? Would be much easier to get the appropriate people involved as this here is highly focused on the SDK itself.

**Comment by quincycs** [comment]
Ok yup.  Ill ask to get on a call about it.
