### ISSUE TITLE
HockeyClient.Flush null ref

### ISSUE THREAD

**Issue by mtaron** [bitstadium/HockeySDK-Windows#80]
In my UWP app, I call `HockeyClient.Current.Flush` when the app enters Background execution, like so:
```csharp
private void OnEnteredBackground(object sender, EnteredBackgroundEventArgs e)
{
    using (e.GetDeferral())
    {
        HockeyClient.Current.Flush();
    }
}
```
 This works well except when the app is opened and closed quickly. In this case, HockeyApp null refs on [this line](https://github.com/bitstadium/HockeySDK-Windows/blob/d0f7b0d3e5c350ddd042d9dea9c87de0444534a0/Src/Kit.Core45/HockeyClient.cs#L1194), despite `HockeyClient.Current.IsTelemetryInitialized` returning true.

**Comment by quincycs** [comment]
@mtaron not a great solution, but I typically put a Task.Delay of 2 or more seconds then flush.  I have this issue as well, but for a different scenario.

**Comment by schuettecarsten** [comment]
@mtaron Why is it useful to call Flush in EnteredBackground?

**Comment by mtaron** [comment]
@schuettecarsten [These docs](https://docs.microsoft.com/en-us/azure/application-insights/app-insights-api-custom-events-metrics) say the following:

> Normally the SDK sends data at times chosen to minimize impact on the user. However, in some cases you might want to flush the buffer - for example, if you are using the SDK in an application that shuts down.

As I understand it, EnteredBackground is the write place to put "pre-shutdown" work in a UWP app. Plus, I aggregate a bunch of rendering performance metrics locally using [RunningStatistics](https://github.com/mathnet/mathnet-numerics/blob/master/src/Numerics/Statistics/RunningStatistics.cs#L50) and I need to choose some place to stop aggregating and report them. It could be elsewhere, but this seemed like a convenient place.

**Comment by schuettecarsten** [comment]
I think that EnteredBackground is also triggered when the application is sent to background but continues to run in the background. If you need to catch the "pre-shutdown" moment, I would use CoreWindow.Closed event which is also documented as "fired when the App terminates" or the Suspend event of the App (which is also fired when the App is closed).

**Comment by mtaron** [comment]
Hm, perhaps. What do you think about the "Save your state" section [here](https://msdn.microsoft.com/en-us/windows/uwp/launch-resume/app-lifecycle#reentering-the-background-state)? Seems like it could apply to flushing telemetry as well.

**Comment by schuettecarsten** [comment]
Ahh, okay, something was added/changed in 1607. Our app has to be compatible to 10240 for next two years, so we cannot use the new APIs.

**Comment by achocron** [comment]
This issue has been resolved with the latest NuGet package releases. Upgrading to 4.1.6 should solve the problem.

**Comment by quincycs** [comment]
@achocron thx.  It fixes the null ref by the look of the code change but now there is a possible side affect that flush might not flush

**Comment by izikl** [comment]
@quincycs yep. We are [postponing the app initialization by 1 sec](https://github.com/bitstadium/HockeySDK-Windows/blob/develop/Src/Kit.Core45/WindowsAppInitializer.cs#L42) to avoid performance hit on app startup. 

We can, however, revise and improve this design. I have opened issue #109 to track it.

**Comment by quincycs** [comment]
Thx.  I'll comment on that
