### ISSUE TITLE
Inconsistent DateTimeOffset parsing from settings

### ISSUE THREAD

**Issue by dkackman** [bitstadium/HockeySDK-Windows#83]
[UserContextInitializer](https://github.com/bitstadium/HockeySDK-Windows/blob/develop/Src/Kit.Core45/UserMetrics/UserContextInitializer.cs#L66) casts userAcquisitionDate directly from object to DateTimeOffset

[SessionTelemetryModule](https://github.com/bitstadium/HockeySDK-Windows/blob/develop/Src/Kit.Core45/UserMetrics/SessionTelemetryModule.cs#L139) casts previousSessionEnd to a string and then calls DateTimeOffset.Parse

This requires an SDK (like WinForms) that is deserializing settings into dictionaries to store one as a DateTimeOffset and the other as a string in order to avoid an InvalidCastException during initialization.

If you agree this is awkward, I can rationalize and provide a PR but need to know which, or if some other, approach is preferred.

**Comment by elamalani** [comment]
@dkackman Is this just refactoring of the code or an error that you are running into? We would like to know more before suggesting an approach.

**Comment by dkackman** [comment]
@elamalani It's a little bit of both. My first attempt to implement a Dictionary based settings collection for used JSON.NET to serialize and deserialize the settings that HockeyApp needs. Since JSON.NET doesn't emit type data it inferred that both user acquisition and the session end were DateTimes. It look like User Aquisition Date is stored as a DateTimeOffset and SessionEnd is stored as a string. 

I changed to using DataContractJsonSerializer, which emits types with the serialization so my custom settings work the same way as the UWP settings collections.

So this can probably be closed as I no longer have the error. Not sure on how important a refactor would be.

**Comment by elamalani** [comment]
Thanks for the update. I will close the issue.
