### ISSUE TITLE
UWP: UnhandledExceptionTelemetryModule.CreateCrashTelemetry should handle AggregateException

### ISSUE THREAD

**Issue by schuettecarsten** [bitstadium/HockeySDK-Windows#85]
When an unhandled exception is caught from Tasks, accoring to the following MSDN link, the exception might not contain a valid information or stack trace data: 
http://stackoverflow.com/questions/32739013/stacktrace-reported-by-unhandledexceptioneventargs-exception-becomes-null-after

So we have some crashes like this:
```
Date/Time:       2016-11-21T13:22:45.159Z
OS Version:      Windows 10.0.14393.447
Report Version:  104

Exception Type:  System.AggregateException
Crashed Thread:  3

Application Specific Information:
TaskExceptionHolder_UnhandledException
```

There are no more information in the crash. So it might be helpful if `UnhandledExceptionTelemetryModule.CreateCrashTelemetry` would handle `AggregateException` and add stack traces and crash details from the inner exceptions of the `AggregateException`.

I also think that `TaskScheduler_UnobservedTaskException` should be unregistered from `TaskScheduler.UnobservedTaskException` in the `Dispose` method of this class.

**Comment by izikl** [comment]
Until there will be a fix for it, you can traverse over the AggregateException using the Description callback:
https://support.hockeyapp.net/discussions/problems/58502-uwp-how-to-call-trackexception?mail_type=queue#comment_40175216

**Comment by quincycs** [comment]
https://github.com/bitstadium/HockeySDK-Windows/issues/61

^related if not same issue.

**Comment by quincycs** [comment]
@schuettecarsten i think this is fixed now.

**Comment by elamalani** [comment]
Closing this issue as it is fixed.
