### ISSUE TITLE
HockeySDK-Windows support for Console applications

### ISSUE THREAD

**Issue by nmklotas** [bitstadium/HockeySDK-Windows#89]
Hello,

I see from the code and from the HockeySDK home page that HockeySDK does not have support for Console applications. 

Is there are any workarounds to use it in Console apps?

Thanks

**Comment by edoust** [comment]
Have a look at PR #88 - with very little code changes you should be good to go.
Mainly what you need to change are the WPF specific classes (e.g. Application.Current) and event handlers (e.g. Application.Exit) - the rest should work fine with console applications as well.

**Comment by elamalani** [comment]
Hi,

We don't have support for console apps in HockeySDK and there is no plan to add the support later on as well. As mentioned by @edoust, using WPF SDK is an option and you can also use WinForms currently in pull request #81 .
