### ISSUE TITLE
Init.ps1 fails in VS2015

### ISSUE THREAD

**Issue by jessenic** [bitstadium/HockeySDK-Windows#91]
Init.ps1 seems to give an error report in the output tab for Package Manager:

    You cannot call a method on a null-valued expression.
    At C:\Users\Jesse Leskinen\.nuget\packages\hockeysdk.uwp\4.1.5\tools\init.ps1:3 char:1
    + $project.DTE.ItemOperations.Navigate('https://github.com/bitstadium/H ...
    + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
        + FullyQualifiedErrorId : InvokeMethodOnNull

**Comment by Eversor** [comment]
Same here, latest nuget package gives this error in the PMC
![immagine](https://cloud.githubusercontent.com/assets/733699/24857057/32a2705e-1de7-11e7-9ac3-aec74c3c1830.png)

**Comment by mfeingol** [comment]
Problem still exists. Please fix.

**Comment by bmourat** [comment]
Fixed in #130
