### ISSUE TITLE
Hockey App Configure fails with object reference not set to an instance on .NET 4.5.2

### ISSUE THREAD

**Issue by JohnGalt1717** [bitstadium/HockeySDK-Windows#92]
I have the following code after installing the nuget package:

```
                HockeyClient.Current.Configure("<key>")
                    .SetContactInfo("Support", "support@xxx.yyy");
```

This fails with a runtime error of "object not found...".

It appears that everything should work because the dependencies are met for nuget but fails. Could someone take a look at see how this can be fixed? (no I can't update it because we're a plugin running inside AutoCAD that is on .NET 4.5.2)

**Comment by bmourat** [comment]
I can't reproduce this, could you please provide more info on this crash and how to reproduce it?
